# config.yaml

# singularity folder
sif_dir: '/mnt/c/Users/c0519/Desktop/ITV/pimba_dev/pimba_smk/sif_files/'

# number of threads
num_threads: 8

# pimba tax
txt_table: '/mnt/c/Users/c0519/Desktop/ITV/pimba_dev/pimba_smk/results/01-run/AllSamples_97clust90assign/AllSamples_asv_table.txt'
fasta_file: '/mnt/c/Users/c0519/Desktop/ITV/pimba_dev/pimba_smk/results/01-run/AllSamples_97clust90assign/AllSamples_asvs.fasta'
raw_reads: '/mnt/c/Users/c0519/Desktop/ITV/pimba_dev/pimba_smk/results/00-prepare/AllSamples.fasta'
outputprepare: 'AllSamples'
outputrun: 'AllSamples_97clust90assign_RDP'
strategy: 'asv'
otu_similarity: 0.97
assign_similarity: 0.9
mincoverage: 0.9
otu_length: 200
hits_per_subject: 5
marker_gene: '16S-RDP'
e_value: 0.001
lulu: 'no'
ITS: 'no'
remote: 'yes'
db_type: 'nt'
create_excel: 'no'
blast_type: 'megablast'

# database files
16S-SILVA-DB: ''
COI-BOLD-DB: ''
16S-GREENGENES-DB: ''
16S-RDP-DB: '/mnt/c/Users/c0519/Desktop/ITV/pimba_dev/RDP/'
NCBI-DB: ''
ITS-FUNGI-UNITE-DB: ''
taxdump: ''
